# API reference https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md
# Refs for v1beta1 config: https://github.com/open-telemetry/opentelemetry-operator/issues/3011#issuecomment-2154118998
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: "0.128.0"
    app.kubernetes.io/component: opentelemetry-operator
spec:
  mode: statefulset
  image: otel/opentelemetry-collector-contrib:0.128.0
  imagePullPolicy: Always
  serviceAccount: otelcontribcol
  autoscaler:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 50
    targetMemoryUtilization: 60
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  env:
    - name: DT_TOKEN
      valueFrom:
        secretKeyRef:
          key: DT_TOKEN
          name: otel-collector-secret
    - name: DT_ENV
      valueFrom:
        secretKeyRef:
          key: DT_ENV
          name: otel-collector-secret
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    # This ain't pretty, but it will do for now
    - name: CLUSTERNAME
      value: "otel-demo"

  config:
    receivers:
      httpcheck/frontend-proxy:
        targets:
        - endpoint: http://frontend-proxy:8080
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${env:MY_POD_IP}:4318

      prometheus:
        config:
          scrape_configs: []
      redis:
        collection_interval: 10s
        endpoint: valkey-cart:6379
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411

      # Logs - Pull k8s objects at given interval, and produce logs
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: pods
            mode: pull
            interval: 30m

      # Collects cluster-level metrics and entity events from the Kubernetes API server
      k8s_cluster:
        node_conditions_to_report: [ Ready, MemoryPressure ]
        allocatable_types_to_report: [ cpu, memory, storage ]
        resource_attributes:
          container.id:
            enabled: false

      # This does the same thing as the Prometheus kube-state-metrics exporter
      # Reference: https://github.com/kubernetes/kube-state-metrics
      # Pulls node, pod, container, and volume metrics from the API server on a kubelet
      kubeletstats:
        collection_interval: 20s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true

    processors:
      batch: {}
      cumulativetodelta: {}

      memory_limiter:
        check_interval: 5s
        limit_percentage: 85
        spike_limit_percentage: 15

      transform:
        error_mode: ignore
        trace_statements: &dynatrace_transformations
          # Set attributes taken from k8s metadata.
          - context: resource
            statements:
              - set(attributes["k8s.cluster.name"], "${env:CLUSTER_NAME}")
              - set(attributes["k8s.workload.kind"], "job") where IsString(attributes["k8s.job.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.job.name"]) where IsString(attributes["k8s.job.name"])
              - set(attributes["k8s.workload.kind"], "cronjob") where IsString(attributes["k8s.cronjob.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.cronjob.name"]) where IsString(attributes["k8s.cronjob.name"])
              - set(attributes["k8s.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["k8s.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["k8s.workload.kind"], "replicaset") where IsString(attributes["k8s.replicaset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.replicaset.name"]) where IsString(attributes["k8s.replicaset.name"])
              - set(attributes["k8s.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              # remove the delete statements if you want to preserve these attributes
              - delete_key(attributes, "k8s.deployment.name")
              - delete_key(attributes, "k8s.replicaset.name")
              - delete_key(attributes, "k8s.statefulset.name")
              - delete_key(attributes, "k8s.daemonset.name")
              - delete_key(attributes, "k8s.cronjob.name")
              - delete_key(attributes, "k8s.job.name")
          # Set attributes from metadata specified in Dynatrace and set through the Dynatrace Operator.
          # For more info: https://docs.dynatrace.com/docs/shortlink/k8s-metadata-telemetry-enrichment
          - context: resource
            statements:
              - merge_maps(attributes, ParseJSON(attributes["metadata.dynatrace.com"]), "upsert") where IsMatch(attributes["metadata.dynatrace.com"], "^\\{")
              - delete_key(attributes, "metadata.dynatrace.com")
        metric_statements: *dynatrace_transformations
        log_statements: *dynatrace_transformations
      k8sattributes:
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.ip
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.job.name
            - k8s.cronjob.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.cluster.uid
            - k8s.container.name
          annotations:
            - from: pod
              key_regex: metadata.dynatrace.com/(.*)
              tag_name: $$1
            - from: pod
              key: metadata.dynatrace.com
              tag_name: metadata.dynatrace.com
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
              
    connectors:
      spanmetrics: {}

    exporters:
      debug:
        verbosity: detailed
      opensearch:
        http:
          endpoint: http://opensearch:9200
          tls:
            insecure: true
        logs_index: otel
      otlp:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true
      otlphttp/dt:
        endpoint: "https://${DT_ENV}/api/v2/otlp"
        headers:
          Authorization: "Api-Token ${DT_TOKEN}"
      otlphttp/prometheus:
        endpoint: http://prometheus:9090/api/v1/otlp
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133


    service:
      extensions:
      - health_check
      pipelines:
        logs:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, transform, batch]
          exporters: [otlphttp/dt, debug]
        metrics:
          receivers: [httpcheck/frontend-proxy, redis, otlp, spanmetrics]
          processors: [k8sattributes, memory_limiter, transform, cumulativetodelta, batch]
          exporters: [otlphttp/dt, debug]
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [k8sattributes, memory_limiter, transform, batch]
          exporters: [otlphttp/dt, debug, spanmetrics]

      telemetry:
        resource:
          k8s.namespace.name: "${env:K8S_POD_NAMESPACE}"
          k8s.pod.name: "${env:K8S_POD_NAME}"
          k8s.node.name: "${env:K8S_NODE_NAME}"

        metrics:
          level: detailed
          readers:
            - periodic:
                interval: 10000
                timeout: 5000            
                exporter:
                  otlp:
                    protocol: http/protobuf
                    temporality_preference: delta
                    endpoint: http://otel-collector.otel-demo.svc.cluster.local:4318
